"""Initial schema with all models

Revision ID: 68e1fcc220f6
Revises: 
Create Date: 2025-11-24 22:46:03.687278

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68e1fcc220f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_boundaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.Integer(), nullable=True, comment='OpenStreetMap ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Tên (Tiếng Việt)'),
    sa.Column('name_en', sa.String(length=255), nullable=True, comment='Tên (Tiếng Anh)'),
    sa.Column('admin_level', sa.Integer(), nullable=False, comment='4=city, 6=district, 8=ward'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='Parent boundary ID'),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True, comment='Dân số'),
    sa.Column('area_km2', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Diện tích (km²)'),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional OSM properties'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_administrative_boundaries_boundary', 'administrative_boundaries', ['boundary'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_administrative_boundaries_admin_level'), 'administrative_boundaries', ['admin_level'], unique=False)
    op.create_index(op.f('ix_administrative_boundaries_id'), 'administrative_boundaries', ['id'], unique=False)
    op.create_index(op.f('ix_administrative_boundaries_osm_id'), 'administrative_boundaries', ['osm_id'], unique=True)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('building_type', sa.String(length=50), nullable=True, comment='residential, commercial, office'),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('height_m', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Chiều cao (m)'),
    sa.Column('levels', sa.Integer(), nullable=True, comment='Số tầng'),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_buildings_geometry', 'buildings', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_index(op.f('ix_buildings_name'), 'buildings', ['name'], unique=False)
    op.create_index(op.f('ix_buildings_osm_id'), 'buildings', ['osm_id'], unique=True)
    op.create_table('environmental_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False, comment='air_quality, weather, noise, traffic'),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Giá trị đo được'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='Đơn vị: µg/m³, °C, dB, km/h'),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm đo'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='waqi, openweathermap, google_maps'),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Thông tin chi tiết: PM2.5, PM10, humidity, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_data_data_type'), 'environmental_data', ['data_type'], unique=False)
    op.create_index(op.f('ix_environmental_data_district_id'), 'environmental_data', ['district_id'], unique=False)
    op.create_index(op.f('ix_environmental_data_id'), 'environmental_data', ['id'], unique=False)
    op.create_index(op.f('ix_environmental_data_measured_at'), 'environmental_data', ['measured_at'], unique=False)
    op.create_table('public_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False, comment='hospital, school, park, police_station, fire_station, library, market'),
    sa.Column('subcategory', sa.String(length=50), nullable=True, comment='Chi tiết: primary_school, general_hospital'),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('opening_hours', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='Sức chứa'),
    sa.Column('rating', sa.DECIMAL(precision=2, scale=1), nullable=True, comment='Đánh giá 0-5'),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True, comment='osm, gov, manual'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_public_facilities_location', 'public_facilities', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_public_facilities_category'), 'public_facilities', ['category'], unique=False)
    op.create_index(op.f('ix_public_facilities_id'), 'public_facilities', ['id'], unique=False)
    op.create_index(op.f('ix_public_facilities_name'), 'public_facilities', ['name'], unique=False)
    op.create_index(op.f('ix_public_facilities_osm_id'), 'public_facilities', ['osm_id'], unique=True)
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('street_type', sa.String(length=50), nullable=True, comment='primary, secondary, residential'),
    sa.Column('district_id', sa.Integer(), nullable=True, comment='Thuộc quận nào'),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('length_m', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Chiều dài (m)'),
    sa.Column('surface', sa.String(length=50), nullable=True, comment='asphalt, concrete'),
    sa.Column('lanes', sa.Integer(), nullable=True, comment='Số làn xe'),
    sa.Column('maxspeed', sa.Integer(), nullable=True, comment='Tốc độ tối đa (km/h)'),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_streets_geometry', 'streets', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_streets_id'), 'streets', ['id'], unique=False)
    op.create_index(op.f('ix_streets_name'), 'streets', ['name'], unique=False)
    op.create_index(op.f('ix_streets_osm_id'), 'streets', ['osm_id'], unique=True)
    op.create_table('transport_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('facility_type', sa.String(length=50), nullable=False, comment='bus_stop, metro_station, taxi_stand, parking'),
    sa.Column('line_number', sa.String(length=20), nullable=True, comment='Số tuyến xe buýt/metro'),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transport_facilities_location', 'transport_facilities', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_transport_facilities_facility_type'), 'transport_facilities', ['facility_type'], unique=False)
    op.create_index(op.f('ix_transport_facilities_id'), 'transport_facilities', ['id'], unique=False)
    op.create_index(op.f('ix_transport_facilities_osm_id'), 'transport_facilities', ['osm_id'], unique=True)
    op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_transport_facilities_osm_id'), table_name='transport_facilities')
    op.drop_index(op.f('ix_transport_facilities_id'), table_name='transport_facilities')
    op.drop_index(op.f('ix_transport_facilities_facility_type'), table_name='transport_facilities')
    op.drop_index('idx_transport_facilities_location', table_name='transport_facilities', postgresql_using='gist')
    op.drop_table('transport_facilities')
    op.drop_index(op.f('ix_streets_osm_id'), table_name='streets')
    op.drop_index(op.f('ix_streets_name'), table_name='streets')
    op.drop_index(op.f('ix_streets_id'), table_name='streets')
    op.drop_index('idx_streets_geometry', table_name='streets', postgresql_using='gist')
    op.drop_table('streets')
    op.drop_index(op.f('ix_public_facilities_osm_id'), table_name='public_facilities')
    op.drop_index(op.f('ix_public_facilities_name'), table_name='public_facilities')
    op.drop_index(op.f('ix_public_facilities_id'), table_name='public_facilities')
    op.drop_index(op.f('ix_public_facilities_category'), table_name='public_facilities')
    op.drop_index('idx_public_facilities_location', table_name='public_facilities', postgresql_using='gist')
    op.drop_table('public_facilities')
    op.drop_index(op.f('ix_environmental_data_measured_at'), table_name='environmental_data')
    op.drop_index(op.f('ix_environmental_data_id'), table_name='environmental_data')
    op.drop_index(op.f('ix_environmental_data_district_id'), table_name='environmental_data')
    op.drop_index(op.f('ix_environmental_data_data_type'), table_name='environmental_data')
    op.drop_table('environmental_data')
    op.drop_index(op.f('ix_buildings_osm_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_name'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_index('idx_buildings_geometry', table_name='buildings', postgresql_using='gist')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_administrative_boundaries_osm_id'), table_name='administrative_boundaries')
    op.drop_index(op.f('ix_administrative_boundaries_id'), table_name='administrative_boundaries')
    op.drop_index(op.f('ix_administrative_boundaries_admin_level'), table_name='administrative_boundaries')
    op.drop_index('idx_administrative_boundaries_boundary', table_name='administrative_boundaries', postgresql_using='gist')
    op.drop_table('administrative_boundaries')
    # ### end Alembic commands ###
